---
Name: palettecolorfieldconfig
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "sitelease/sl-palette-color-field:client/dist/styles/bundle.css"
  extra_requirements_javascript:
    - "sitelease/sl-palette-color-field:client/dist/js/bundle.js"
